-
  branches:
    only:
    - master
  
  version: 0.1.0

  image: Visual Studio 2015
      
  init:
  - git config --global core.autocrlf input
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      
  skip_tags: true
  
  configuration: Release
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
  
  install:
  - appveyor-retry npm install npm -g
  - appveyor-retry npm install -g bower
  - appveyor-retry npm install -g gulp

  before_build:
  - appveyor-retry npm install
  - appveyor-retry bower install
  - ps: .\dotnet-restore.ps1

  build:
    project: Blongo.sln
    parallel: true

  test_script:
  - ps: .\dotnet-test.ps1
  - ps: >
      $webClient = New-Object 'System.Net.WebClient';
      Get-ChildItem artifacts\test -include TestResult.xml -recurse | % { $webClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", $_.FullName) }
  
  deploy_script:
  - ps: .\dotnet-publish.ps1
  - '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp=''%APPVEYOR_BUILD_FOLDER%\artifacts\publish'' -dest:IisApp=''blongo'',ComputerName=''https://blongo.scm.azurewebsites.net/msdeploy.axd?site=blongo'',UserName=''%WEB_DEPLOY_USERNAME%'',Password=''%WEB_DEPLOY_PASSWORD%'',IncludeAcls=''False'',AuthType=''Basic'' -verb:sync -enablerule:AppOffline -retryAttempts:20'

  on_success:
  - git config --global user.email "%GIT_EMAIL_ADDRESS"
  - git config --global user.name "%GIT_USERNAME%"
  - git config --global credential.helper store
  - ps: Add-Content "$Env:USERPROFILE\.git-credentials" "https://$($Env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git remote add GitHub https://github.com/%APPVEYOR_REPO_NAME%.git
  - git tag %APPVEYOR_BUILD_VERSION% %APPVEYOR_REPO_COMMIT%
  - git push --tags --quiet

  on_failure:
  - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"

  on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))